### ISSUE TITLE
error : Installing "cordova-zebra-scanner" for android

### ISSUE THREAD

**Issue by setijo** [michael-may/cordova-zebra-scanner#3]
D:\cordova\UBSRFID>cordova plugin add cordova-zebra-scanner
Installing "cordova-zebra-scanner" for android
Failed to install 'cordova-zebra-scanner': Error: ENOENT: no such file or directory, open 'D:\cordova\UBSRFID\platforms\android\AndroidManifest.xml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.parseElementtreeSync 

(D:\cordova\UBSRFID\platforms\android\cordova\node_modules\cordova-common\src\util\xml-helpers.js:180:27)
    at new AndroidManifest 

(D:\cordova\UBSRFID\platforms\android\cordova\lib\AndroidManifest.js:29:20)
    at AndroidProject.getPackageName 

(D:\cordova\UBSRFID\platforms\android\cordova\lib\AndroidProject.js:99:12)
    at Api.addPlugin (D:\cordova\UBSRFID\platforms\android\cordova\Api.js:223:57)
    at handleInstall 

(C:\Users\SEAG\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:594:10)
    at C:\Users\SEAG\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:357:28
    at _fulfilled (C:\Users\SEAG\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done 
(C:\Users\SEAG\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\q\q.js:816:30)
(node:8836) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: ENOENT: no such file or directory, open 'D:\cordova\UBSRFID\
platforms\android\AndroidManifest.xml'
(node:8836) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

D:\cordova\UBSRFID>cordova --version
8.0.0
D:\cordova\UBSRFID>node --version
v8.9.1

**Comment by setijo** [comment]
today I resolved the error with downgrade android, following the steps :

D:\cordova>cordova create UBSRFID com.seagubsrfid.com UBSRFID
D:\cordova>cd UBSRFID
**D:\cordova\UBSRFID>cordova platform add android@6.4.0** 
D:\cordova\UBSRFID>cordova build
D:\cordova\UBSRFID>cordova plugin add cordova-zebra-scanner
D:\cordova\UBSRFID>cordova plugin add cordova-plugin-backbutton
D:\cordova\UBSRFID>cordova plugin list
cordova-plugin-backbutton 0.3.0 "Backbutton"
cordova-plugin-whitelist 1.3.3 "Whitelist"
**cordova-zebra-scanner 1.0.3 "Zebra Barcode Scanner Plugin"**

D:\cordova\UBSRFID>cordova compile
